theme: minima
title: Choral Music
author: jostle
email: jostle@jostlesoft.com
description: > # this means to ignore newlines until "baseurl:"
  This is the place to come for Classical Choral Music!

# social links
github_username:  jostle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
